networks:
  backend_net:
    driver: bridge

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - backend_db
    networks:
      - backend_net
    env_file:
      - .env
    # environment:
    #   - DATABASE_URL=postgres://postgres:postgres@Db :5432/postgres
    #   - NODE_ENV=development
  
  backend_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - backend_net
